name: Krypton Build (Windows)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up MinGW
        run: |
          echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
          echo "C:\msys64\mingw64\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Dependencies
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-pdcurses
          pacman -S --noconfirm mingw-w64-x86_64-openssl

      - name: Create Required Directories
        run: |
          mkdir -p build/obj/command
          mkdir -p build/obj/core
          mkdir -p build/obj/utils
          mkdir -p build/bin
          mkdir -p assets/resources
          mkdir -p assets/icons

      - name: Build Krypton
        shell: cmd
        run: |
          mingw32-make clean
          mingw32-make

      - name: Verify Build
        shell: cmd
        run: |
          if exist build\bin\krypton.exe (
            echo ✅ Build Successful !
          ) else (
            echo ❌ Build Failed ! & exit 1
          )
