name: Krypton Build (Windows)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up MinGW
        run: echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Build Krypton
        shell: cmd  # Use Windows Command Prompt
        run: |
          mingw32-make clean
          mingw32-make

      - name: Verify Build
        shell: cmd  # Use Windows Command Prompt
        run: |
          if exist build\bin\krypton.exe (
            echo ✅ Build Successful !
          ) else (
            echo ❌ Build Failed ! & exit 1
          )
